export const countries = [
    { id: 'Afganistán', name: 'Afganistán' },
    { id: 'Albania', name: 'Albania' },
    { id: 'Alemania', name: 'Alemania' },
    { id: 'Andorra', name: 'Andorra' },
    { id: 'Angola', name: 'Angola' },
    { id: 'Antigua y Barbuda', name: 'Antigua y Barbuda' },
    { id: 'Arabia Saudita', name: 'Arabia Saudita' },
    { id: 'Argelia', name: 'Argelia' },
    { id: 'Argentina', name: 'Argentina' },
    { id: 'Armenia', name: 'Armenia' },
    { id: 'Australia', name: 'Australia' },
    { id: 'Austria', name: 'Austria' },
    { id: 'Azerbaiyán', name: 'Azerbaiyán' },
    { id: 'Bahamas', name: 'Bahamas' },
    { id: 'Bangladés', name: 'Bangladés' },
    { id: 'Barbados', name: 'Barbados' },
    { id: 'Baréin', name: 'Baréin' },
    { id: 'Bélgica', name: 'Bélgica' },
    { id: 'Belice', name: 'Belice' },
    { id: 'Benín', name: 'Benín' },
    { id: 'Bielorrusia', name: 'Bielorrusia' },
    { id: 'Birmania', name: 'Birmania' },
    { id: 'Bolivia', name: 'Bolivia' },
    { id: 'Bosnia y Herzegovina', name: 'Bosnia y Herzegovina' },
    { id: 'Botsuana', name: 'Botsuana' },
    { id: 'Brasil', name: 'Brasil' },
    { id: 'Brunéi', name: 'Brunéi' },
    { id: 'Bulgaria', name: 'Bulgaria' },
    { id: 'Burkina Faso', name: 'Burkina Faso' },
    { id: 'Burundi', name: 'Burundi' },
    { id: 'Bután', name: 'Bután' },
    { id: 'Cabo Verde', name: 'Cabo Verde' },
    { id: 'Camboya', name: 'Camboya' },
    { id: 'Camerún', name: 'Camerún' },
    { id: 'Canadá', name: 'Canadá' },
    { id: 'Catar', name: 'Catar' },
    { id: 'Chad', name: 'Chad' },
    { id: 'Chile', name: 'Chile' },
    { id: 'China', name: 'China' },
    { id: 'Chipre', name: 'Chipre' },
    { id: 'Ciudad del Vaticano', name: 'Ciudad del Vaticano' },
    { id: 'Colombia', name: 'Colombia' },
    { id: 'Comoras', name: 'Comoras' },
    { id: 'Corea del Norte', name: 'Corea del Norte' },
    { id: 'Corea del Sur', name: 'Corea del Sur' },
    { id: 'Costa de Marfil', name: 'Costa de Marfil' },
    { id: 'Costa Rica', name: 'Costa Rica' },
    { id: 'Croacia', name: 'Croacia' },
    { id: 'Cuba', name: 'Cuba' },
    { id: 'Dinamarca', name: 'Dinamarca' },
    { id: 'Dominica', name: 'Dominica' },
    { id: 'Ecuador', name: 'Ecuador' },
    { id: 'Egipto', name: 'Egipto' },
    { id: 'El Salvador', name: 'El Salvador' },
    { id: 'Emiratos Árabes Unidos', name: 'Emiratos Árabes Unidos' },
    { id: 'Eritrea', name: 'Eritrea' },
    { id: 'Eslovaquia', name: 'Eslovaquia' },
    { id: 'Eslovenia', name: 'Eslovenia' },
    { id: 'España', name: 'España' },
    { id: 'Estados Unidos', name: 'Estados Unidos' },
    { id: 'Estonia', name: 'Estonia' },
    { id: 'Etiopía', name: 'Etiopía' },
    { id: 'Filipinas', name: 'Filipinas' },
    { id: 'Finlandia', name: 'Finlandia' },
    { id: 'Fiyi', name: 'Fiyi' },
    { id: 'Francia', name: 'Francia' },
    { id: 'Gabón', name: 'Gabón' },
    { id: 'Gambia', name: 'Gambia' },
    { id: 'Georgia', name: 'Georgia' },
    { id: 'Ghana', name: 'Ghana' },
    { id: 'Granada', name: 'Granada' },
    { id: 'Grecia', name: 'Grecia' },
    { id: 'Guatemala', name: 'Guatemala' },
    { id: 'Guyana', name: 'Guyana' },
    { id: 'Guinea', name: 'Guinea' },
    { id: 'Guinea ecuatorial', name: 'Guinea ecuatorial' },
    { id: 'Guinea-Bisáu', name: 'Guinea-Bisáu' },
    { id: 'Haití', name: 'Haití' },
    { id: 'Honduras', name: 'Honduras' },
    { id: 'Hungría', name: 'Hungría' },
    { id: 'India', name: 'India' },
    { id: 'Indonesia', name: 'Indonesia' },
    { id: 'Irak', name: 'Irak' },
    { id: 'Irán', name: 'Irán' },
    { id: 'Irlanda', name: 'Irlanda' },
    { id: 'Islandia', name: 'Islandia' },
    { id: 'Islas Marshall', name: 'Islas Marshall' },
    { id: 'Islas Salomón', name: 'Islas Salomón' },
    { id: 'Israel', name: 'Israel' },
    { id: 'Italia', name: 'Italia' },
    { id: 'Jamaica', name: 'Jamaica' },
    { id: 'Japón', name: 'Japón' },
    { id: 'Jordania', name: 'Jordania' },
    { id: 'Kazajistán', name: 'Kazajistán' },
    { id: 'Kenia', name: 'Kenia' },
    { id: 'Kirguistán', name: 'Kirguistán' },
    { id: 'Kiribati', name: 'Kiribati' },
    { id: 'Kuwait', name: 'Kuwait' },
    { id: 'Laos', name: 'Laos' },
    { id: 'Lesoto', name: 'Lesoto' },
    { id: 'Letonia', name: 'Letonia' },
    { id: 'Líbano', name: 'Líbano' },
    { id: 'Liberia', name: 'Liberia' },
    { id: 'Libia', name: 'Libia' },
    { id: 'Liechtenstein', name: 'Liechtenstein' },
    { id: 'Lituania', name: 'Lituania' },
    { id: 'Luxemburgo', name: 'Luxemburgo' },
    { id: 'Madagascar', name: 'Madagascar' },
    { id: 'Malasia', name: 'Malasia' },
    { id: 'Malaui', name: 'Malaui' },
    { id: 'Maldivas', name: 'Maldivas' },
    { id: 'Malí', name: 'Malí' },
    { id: 'Malta', name: 'Malta' },
    { id: 'Marruecos', name: 'Marruecos' },
    { id: 'Mauricio', name: 'Mauricio' },
    { id: 'Mauritania', name: 'Mauritania' },
    { id: 'México', name: 'México' },
    { id: 'Micronesia', name: 'Micronesia' },
    { id: 'Moldavia', name: 'Moldavia' },
    { id: 'Mónaco', name: 'Mónaco' },
    { id: 'Mongolia', name: 'Mongolia' },
    { id: 'Montenegro', name: 'Montenegro' },
    { id: 'Mozambique', name: 'Mozambique' },
    { id: 'Namibia', name: 'Namibia' },
    { id: 'Nauru', name: 'Nauru' },
    { id: 'Nepal', name: 'Nepal' },
    { id: 'Nicaragua', name: 'Nicaragua' },
    { id: 'Níger', name: 'Níger' },
    { id: 'Nigeria', name: 'Nigeria' },
    { id: 'Noruega', name: 'Noruega' },
    { id: 'Nueva Zelanda', name: 'Nueva Zelanda' },
    { id: 'Omán', name: 'Omán' },
    { id: 'Países Bajos', name: 'Países Bajos' },
    { id: 'Pakistán', name: 'Pakistán' },
    { id: 'Palaos', name: 'Palaos' },
    { id: 'Panamá', name: 'Panamá' },
    { id: 'Papúa Nueva Guinea', name: 'Papúa Nueva Guinea' },
    { id: 'Paraguay', name: 'Paraguay' },
    { id: 'Perú', name: 'Perú' },
    { id: 'Polonia', name: 'Polonia' },
    { id: 'Portugal', name: 'Portugal' },
    { id: 'Reino Unido', name: 'Reino Unido' },
    { id: 'República Centroafricana', name: 'República Centroafricana' },
    { id: 'República Checa', name: 'República Checa' },
    { id: 'República Democrática del Congo', name: 'República Democrática del Congo' },
    { id: 'República Dominicana', name: 'República Dominicana' },
    { id: 'Ruanda', name: 'Ruanda' },
    { id: 'Rumanía', name: 'Rumanía' },
    { id: 'Rusia', name: 'Rusia' },
    { id: 'Samoa', name: 'Samoa' },
    { id: 'San Cristóbal y Nieves', name: 'San Cristóbal y Nieves' },
    { id: 'San Marino', name: 'San Marino' },
    { id: 'San Vicente y las Granadinas', name: 'San Vicente y las Granadinas' },
    { id: 'Santa Lucía', name: 'Santa Lucía' },
    { id: 'Santo Tomé y Príncipe', name: 'Santo Tomé y Príncipe' },
    { id: 'Senegal', name: 'Senegal' },
    { id: 'Serbia', name: 'Serbia' },
    { id: 'Seychelles', name: 'Seychelles' },
    { id: 'Sierra Leona', name: 'Sierra Leona' },
    { id: 'Singapur', name: 'Singapur' },
    { id: 'Siria', name: 'Siria' },
    { id: 'Somalia', name: 'Somalia' },
    { id: 'Sri Lanka', name: 'Sri Lanka' },
    { id: 'Suazilandia', name: 'Suazilandia' },
    { id: 'Sudáfrica', name: 'Sudáfrica' },
    { id: 'Sudán', name: 'Sudán' },
    { id: 'Sudán del Sur', name: 'Sudán del Sur' },
    { id: 'Suecia', name: 'Suecia' },
    { id: 'Suiza', name: 'Suiza' },
    { id: 'Surinam', name: 'Surinam' },
    { id: 'Tailandia', name: 'Tailandia' },
    { id: 'Tanzania', name: 'Tanzania' },
    { id: 'Tayikistán', name: 'Tayikistán' },
    { id: 'Timor Oriental', name: 'Timor Oriental' },
    { id: 'Togo', name: 'Togo' },
    { id: 'Tonga', name: 'Tonga' },
    { id: 'Trinidad y Tobago', name: 'Trinidad y Tobago' },
    { id: 'Túnez', name: 'Túnez' },
    { id: 'Turkmenistán', name: 'Turkmenistán' },
    { id: 'Turquía', name: 'Turquía' },
    { id: 'Tuvalu', name: 'Tuvalu' },
    { id: 'Ucrania', name: 'Ucrania' },
    { id: 'Uganda', name: 'Uganda' },
    { id: 'Uruguay', name: 'Uruguay' },
    { id: 'Uzbekistán', name: 'Uzbekistán' },
    { id: 'Vanuatu', name: 'Vanuatu' },
    { id: 'Venezuela', name: 'Venezuela' },
    { id: 'Vietnam', name: 'Vietnam' },
    { id: 'Yemen', name: 'Yemen' },
    { id: 'Yibuti', name: 'Yibuti' },
    { id: 'Zambia', name: 'Zambia' },
    { id: 'Zimbabue', name: 'Zimbabue' }
  ];